### PR TITLE
Hello world example

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by deadtrickster** [comment]
Shouldn't we have tests for examples as well? People usually copy pasting and the getting upset if something doesn't work.

**Comment by lpil** [comment]
For sure.

How about an eunit test that makes a request using httpc?

**Comment by deadtrickster** [comment]
I think it's a good idea. I like httpc because it's always there.

**Comment by lpil** [comment]
Pushed a test. I also included a travis config for when we enable CI

**Comment by deadtrickster** [comment]
Thanks! Also enabled Travis

**Comment by yurrriq** [comment]
:tada: thanks!

**Comment by lpil** [comment]
Thanks all

**Pull request merged**
